services:
  postgresdb:
    image: postgres:17
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: nikhil
      POSTGRES_PASSWORD: pollstack
      POSTGRES_DB: pollstack
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  valkey:
    image: valkey/valkey
    ports:
      - 6379:6379

volumes:
  postgres_data:
